// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/language-variants/Conversation.tsx": () => import("../components/mockups/language-variants/Conversation.tsx"),
  "./components/mockups/language-variants/Editorial.tsx": () => import("../components/mockups/language-variants/Editorial.tsx"),
  "./components/mockups/language-variants/Immersive.tsx": () => import("../components/mockups/language-variants/Immersive.tsx"),
  "./components/mockups/language-variants/Swipe.tsx": () => import("../components/mockups/language-variants/Swipe.tsx")
};
